name: JuliaStable
on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:

jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.5"
      - name: Force update registry
        run: julia -e 'using Pkg; Pkg.Registry.rm("General"); Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaRegistries/General"))'
      - name: Install Dependencies
        run: julia --project -e 'ENV["PYTHON"]=""; using Pkg; Pkg.instantiate();'
      - name: Run Tests
        uses: julia-actions/julia-runtest@latest
      - name: Process Coverage
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          file: lcov.info
  macos-test:
    runs-on: macos-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.5"
      - name: Force update registry
        run: julia -e 'using Pkg; Pkg.Registry.rm("General"); Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaRegistries/General"))'
      - name: Install Dependencies
        run: julia --project -e 'ENV["PYTHON"]=""; using Pkg; Pkg.instantiate();'
      - name: Run Tests
        uses: julia-actions/julia-runtest@latest
  windows-test:
    runs-on: windows-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.5"
      - name: Force update registry
        run: julia -e 'using Pkg; Pkg.Registry.rm(\"General\"); Pkg.Registry.add(RegistrySpec(url=\"https://github.com/JuliaRegistries/General\"))'
      - name: Install Dependencies
        run: julia --project -e 'ENV[\"PYTHON\"]=\"\"; using Pkg; Pkg.instantiate();'
      - name: Run Tests
        uses: julia-actions/julia-runtest@latest
