name: Julia-1.4
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  version-support-1-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.4'
      - run: julia --project -e 'using Pkg; Pkg.test();'
